# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  phonebook_report_api:
    image: phonebook-report-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
